version: '3'

networks:
    gateway:
        external: true

services:
    wapen-web:
        container_name: wapen-web
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - TZ=Asia/Shanghai
        labels:
            - traefik.enable=true
            - traefik.http.routers.wapen-web.rule=Host(`wapenai.cn`)
            - traefik.http.services.wapen-web.loadbalancer.server.port=8080
            - traefik.http.routers.wapen-web.tls=true
            - traefik.http.routers.wapen-web.tls.certresolver=letsencrypt
        privileged: true
        stdin_open: true
        tty: true
        networks:
            - gateway
        restart: always
